# Generated by Django 5.0 on 2023-12-21 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.CharField(choices=[('Tarix', '#Tarix'), ('Sport', '#Sport'), ('Phone', '#Phone'), ('Siyosat', '#Siyosat'), ('Madaniy', '#Madaniy'), ('Kitob', '#Kitob')], default='tarix', max_length=20)),
                ('question', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('comment_count', models.PositiveIntegerField(default=0)),
                ('likes', models.ManyToManyField(related_name='tweet_like', to=settings.AUTH_USER_MODEL)),
                ('parent_tweet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tweet.tweet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tweet.tweet')),
            ],
        ),
    ]
