# Generated by Django 5.0 on 2023-12-21 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, default='https://www.instagram.com/p/C1AzlKiI0IW/', null=True, upload_to='profile_img/')),
                ('fullname', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=15)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usermodel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
